package otus.gpb.recyclerview

class FillData {
    fun getData(): MutableList<ItemData> {
        return mutableListOf(
            ItemData(
                R.drawable.avatar,
                "Pizza",
                "Yes, they are necessary",
                "11:38 AM",
                "jija",
                isMute = true,
                isVerify = false,
                isScam = false,
                isCheck = false,
                isDoubleCheck = false,
                unreadCount = 0,
                unreadIcon = false
            ),
            ItemData(
                R.drawable.avatar_1,
                "Elon",
                "I love /r/Reddit!",
                "12:44 AM",
                "",
                isMute = true,
                isVerify = false,
                isScam = false,
                isCheck = false,
                isDoubleCheck = false,
                unreadCount = 0,
                unreadIcon = false
            ),
            ItemData(
                R.drawable.avatar_2,
                "Pasha",
                "How are u?",
                "Fri",
                "",
                isMute = true,
                isVerify = true,
                isScam = false,
                isCheck = false,
                isDoubleCheck = false,
                unreadCount = 0,
                unreadIcon = false
            ),
            ItemData(
                R.drawable.avatar_3,
                "Otus",
                "Doin my homework",
                "Thu",
                "helicopterpak",
                isMute = false,
                isVerify = false,
                isScam = false,
                isCheck = false,
                isDoubleCheck = true,
                unreadCount = 0,
                unreadIcon = false
            ),
            ItemData(
                R.drawable.avatar_3,
                "Telegram Support",
                "Yes it happend.",
                "Thu",
                "Support",
                isMute = false,
                isVerify = true,
                isScam = false,
                isCheck = false,
                isDoubleCheck = false,
                unreadCount = 1,
                unreadIcon = true
            ),
            ItemData(
                R.drawable.avatar_4,
                "Karina",
                "Okay",
                "Wed",
                "",
                isMute = false,
                isVerify = false,
                isScam = false,
                isCheck = true,
                isDoubleCheck = false,
                unreadCount = 0,
                unreadIcon = false
            ),
            ItemData(
                R.drawable.avatar_5,
                "Marilyn",
                "Will it ever happen",
                "May 02",
                "",
                isMute = false,
                isVerify = false,
                isScam = true,
                isCheck = false,
                isDoubleCheck = true,
                unreadCount = 0,
                unreadIcon = false
            )
    //            ,
//            ItemData(
//                R.drawable.avatar_3,
//                "Pizza",
//                "Yes, they are necessary",
//                "11:38 AM",
//                "jija",
//                isMute = true,
//                isVerify = false,
//                isScam = false,
//                isCheck = false,
//                isDoubleCheck = false,
//                unreadCount = 0,
//                unreadIcon = false
//            ),
//            ItemData(
//                R.drawable.avatar_3,
//                "Elon",
//                "I love /r/Reddit!",
//                "12:44 AM",
//                "",
//                isMute = true,
//                isVerify = false,
//                isScam = false,
//                isCheck = false,
//                isDoubleCheck = false,
//                unreadCount = 0,
//                unreadIcon = false
//            ),
//            ItemData(
//                R.drawable.avatar_3,
//                "Pasha",
//                "How are u?",
//                "Fri",
//                "",
//                isMute = true,
//                isVerify = true,
//                isScam = false,
//                isCheck = false,
//                isDoubleCheck = false,
//                unreadCount = 0,
//                unreadIcon = false
//            ),
//            ItemData(
//                R.drawable.avatar_3,
//                "Otus",
//                "Doin my homework",
//                "Thu",
//                "helicopterpak",
//                isMute = false,
//                isVerify = false,
//                isScam = false,
//                isCheck = false,
//                isDoubleCheck = true,
//                unreadCount = 0,
//                unreadIcon = false
//            ),
//            ItemData(
//                R.drawable.avatar_3,
//                "Telegram Support",
//                "Yes it happend.",
//                "Thu",
//                "Support",
//                isMute = false,
//                isVerify = true,
//                isScam = false,
//                isCheck = false,
//                isDoubleCheck = false,
//                unreadCount = 1,
//                unreadIcon = true
//            ),
//            ItemData(
//                R.drawable.avatar_3,
//                "Karina",
//                "Okay",
//                "Wed",
//                "",
//                isMute = false,
//                isVerify = false,
//                isScam = false,
//                isCheck = true,
//                isDoubleCheck = false,
//                unreadCount = 0,
//                unreadIcon = false
//            ),
//            ItemData(
//                R.drawable.avatar_3,
//                "Marilyn",
//                "Will it ever happen",
//                "May 02",
//                "",
//                isMute = false,
//                isVerify = false,
//                isScam = true,
//                isCheck = false,
//                isDoubleCheck = true,
//                unreadCount = 0,
//                unreadIcon = false
//            ),
//            ItemData(
//                R.drawable.avatar,
//                "Pizza",
//                "Yes, they are necessary",
//                "11:38 AM",
//                "jija",
//                isMute = true,
//                isVerify = false,
//                isScam = false,
//                isCheck = false,
//                isDoubleCheck = false,
//                unreadCount = 0,
//                unreadIcon = false
//            ),
//            ItemData(
//                R.drawable.avatar,
//                "Elon",
//                "I love /r/Reddit!",
//                "12:44 AM",
//                "",
//                isMute = true,
//                isVerify = false,
//                isScam = false,
//                isCheck = false,
//                isDoubleCheck = false,
//                unreadCount = 0,
//                unreadIcon = false
//            ),
//            ItemData(
//                R.drawable.avatar,
//                "Pasha",
//                "How are u?",
//                "Fri",
//                "",
//                isMute = true,
//                isVerify = true,
//                isScam = false,
//                isCheck = false,
//                isDoubleCheck = false,
//                unreadCount = 0,
//                unreadIcon = false
//            ),
//            ItemData(
//                R.drawable.avatar,
//                "Otus",
//                "Doin my homework",
//                "Thu",
//                "helicopterpak",
//                isMute = false,
//                isVerify = false,
//                isScam = false,
//                isCheck = false,
//                isDoubleCheck = true,
//                unreadCount = 0,
//                unreadIcon = false
//            ),
//            ItemData(
//                R.drawable.avatar,
//                "Telegram Support",
//                "Yes it happend.",
//                "Thu",
//                "Support",
//                isMute = false,
//                isVerify = true,
//                isScam = false,
//                isCheck = false,
//                isDoubleCheck = false,
//                unreadCount = 1,
//                unreadIcon = true
//            ),
//            ItemData(
//                R.drawable.avatar,
//                "Karina",
//                "Okay",
//                "Wed",
//                "",
//                isMute = false,
//                isVerify = false,
//                isScam = false,
//                isCheck = true,
//                isDoubleCheck = false,
//                unreadCount = 0,
//                unreadIcon = false
//            ),
//            ItemData(
//                R.drawable.avatar,
//                "Marilyn",
//                "Will it ever happen",
//                "May 02",
//                "",
//                isMute = false,
//                isVerify = false,
//                isScam = true,
//                isCheck = false,
//                isDoubleCheck = true,
//                unreadCount = 0,
//                unreadIcon = false
//            )


        )

    }
}